version: '3.8'

services:
  aware-backend:
    build: .
    container_name: aware-backend
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
    environment:
      - NODE_ID=${NODE_ID:-node-1}
      - DISCOVERY_PORT=${DISCOVERY_PORT:-41234}
      - BROADCAST_PORT=${BROADCAST_PORT:-41235}
      - API_PORT=${API_PORT:-3000}
      - NODE_LIST=${NODE_LIST:-}
      - SECRET_KEY=${SECRET_KEY:-default_secure_key_for_deployment}
    volumes:
      - ./data:/app/data  # For persistent data
    networks:
      - aware-network
    restart: unless-stopped

  aware-frontend:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: aware-frontend
    ports:
      - "3001:80"  # Serve frontend separately on port 3001
    depends_on:
      - aware-backend
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:${API_PORT:-3000}/api}
    networks:
      - aware-network
    restart: unless-stopped

networks:
  aware-network:
    driver: bridge

volumes:
  aware_data: