// SPDX-License-Identifier: Apache-2.0
// ISO/IEC 42001:2023 — AWARE Compliance Catalog
//
// Control IDs and titles sourced from ISMS.online's public summary of
// ISO/IEC 42001:2023 Annex A:
//   https://www.isms.online/iso-42001/annex-a-controls/
//   (fetched 2026-07-28; 38-control subset of the 42-control official Annex A)
//
// Short descriptions are paraphrased and not derived from ISO's normative
// text. ISO/IEC 42001:2023 is the property of ISO and is NOT Creative
// Commons — the catalog does not reproduce ISO standard text.
//
// Pin discipline: any ISO corrigendum or amendment that adds/renumbers
// controls is a NEW AWARE release; do NOT edit this file in place.
// Mid-cycle upstream changes are a coordinated update via the snapshot
// script (scripts/snapshot-iso42001-catalog.js).
//
// AWARE does NOT claim ISO/IEC 42001:2023 certification. The framework-mapper
// entry is a control-coverage assertion, not a certification claim.
//
// Per ADR-055 §D3, each control carries an `awareness` class:
//   - 'mapped'   AWARE directly emits the evidence (H confidence, research §4)
//   - 'partial'  AWARE contributes but is not the primary evidence source (M)
//   - 'gap'      No AWARE surface (L); org-level concerns or follow-up modules
//
// Per ADR-055 §D2, the SPDX stays Apache-2.0 (the catalog is AWARE-authored
// code); the third-party attribution to ISMS.online travels as this comment
// block — the SPDX tooling that license-checks code files would mis-classify
// the catalog if the SPDX itself read "CC" or "ISO licensed".
//
// 38-vs-42 gap: ISO/IEC 42001:2023 Annex A officially has 42 controls per
// multiple secondary references. ISMS.online's public nav list enumerates
// 38 with stable IDs (the 4 missing are most likely sub-controls that
// ISMS consolidates under parent titles). The v1 catalog ships 38; a future
// researcher card reconciles against the official Annex A when an operator
// has access. See ADR-055 §"Source pinning" and §"Corrections".

'use strict';

/**
 * @typedef {Object} ISO42001CatalogEntry
 * @property {string} name                - short control title (from ISMS.online)
 * @property {string} description         - paraphrased description (≤200 chars,
 *                                          NOT lifted from ISO normative text)
 * @property {'mapped'|'partial'|'gap'} awareness  - AWARE's coverage class
 * @property {string[]} awareComponents   - primary AWARE evidence sources
 *                                          (0+ component IDs from
 *                                          AWARE_COMPONENT_MAPPINGS)
 * @property {'H'|'M'|'L'} crosswalkConfidence - verbatim from research §4
 * @property {string} ismsRef             - canonical URL on ISMS.online
 *                                          (https://www.isms.online/iso-42001/annex-a-controls/#a-X-Y-Z)
 * @property {string} clause              - ISO/IEC 42001 Annex A clause heading
 *                                          (e.g., "A.6 — AI system lifecycle")
 */

/**
 * ISO/IEC 42001:2023 Annex A — 38-control subset per ISMS.online.
 *
 * Field provenance:
 *   - name / ismsRef           → ISMS.online public summary (third-party mirror).
 *   - description              → first-party AWARE characterization, paraphrased.
 *                                ≤200 chars. No ISO normative text reproduced.
 *   - awareness / awareComponents / crosswalkConfidence → AWARE research §4.
 *   - clause                   → ISO/IEC 42001 Annex A clause heading (factual).
 *
 * DO NOT invent new control IDs. If a corrigendum / amendment adds or
 * renumbers a control, create a new catalogue version per ADR-055 §D1.
 *
 * @type {Object<string, ISO42001CatalogEntry>}
 */
const ISO_42001_CONTROLS = Object.freeze({

  // -----------------------------------------------------------------------
  // A.2 — Policies for AI
  // -----------------------------------------------------------------------
  'A.2.2': {
    name: 'AI Policy',
    description: 'Top-level AI policy defining objectives, scope, and principles for AI use within the organisation.',
    awareness: 'partial',
    awareComponents: ['compliance-mapping'],
    crosswalkConfidence: 'M',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-2-2',
    clause: 'A.2 — Policies for AI'
  },
  'A.2.3': {
    name: 'Alignment With Other Organisational Policies',
    description: 'AI policy consistent with and cross-referenced to existing infosec, quality, and risk policies.',
    awareness: 'partial',
    awareComponents: ['compliance-mapping'],
    crosswalkConfidence: 'M',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-2-3',
    clause: 'A.2 — Policies for AI'
  },
  'A.2.4': {
    name: 'Review of the AI Policy',
    description: 'AI policy reviewed at planned intervals and after significant changes; review outcome documented.',
    awareness: 'gap',
    awareComponents: [],
    crosswalkConfidence: 'L',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-2-4',
    clause: 'A.2 — Policies for AI'
  },

  // -----------------------------------------------------------------------
  // A.3 — Internal organization
  // -----------------------------------------------------------------------
  'A.3.2': {
    name: 'AI Roles and Responsibilities',
    description: 'Defined roles, responsibilities, and authorities for AI development, deployment, and oversight.',
    awareness: 'mapped',
    awareComponents: ['agent-registry', 'identity-provider'],
    crosswalkConfidence: 'H',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-3-2',
    clause: 'A.3 — Internal organization'
  },
  'A.3.3': {
    name: 'Reporting of Concerns',
    description: 'Mechanism for staff and users to raise concerns about AI systems without retaliation.',
    awareness: 'partial',
    awareComponents: ['tool-observation-proxy', 'anomaly-detection'],
    crosswalkConfidence: 'M',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-3-3',
    clause: 'A.3 — Internal organization'
  },

  // -----------------------------------------------------------------------
  // A.4 — Resources
  // -----------------------------------------------------------------------
  'A.4.2': {
    name: 'Resource Documentation',
    description: 'Documented inventory of AI resources (data, models, compute, tooling) used by the organisation.',
    awareness: 'mapped',
    awareComponents: ['agent-registry'],
    crosswalkConfidence: 'H',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-4-2',
    clause: 'A.4 — Resources'
  },
  'A.4.3': {
    name: 'Data Resources',
    description: 'Identified and documented datasets used to train, validate, and operate AI systems.',
    awareness: 'partial',
    awareComponents: ['agent-registry', 'tool-observation-proxy'],
    crosswalkConfidence: 'M',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-4-3',
    clause: 'A.4 — Resources'
  },
  'A.4.4': {
    name: 'Tooling Resources',
    description: 'Documented AI development and deployment tools, including version and provenance information.',
    awareness: 'mapped',
    awareComponents: ['tool-access-control'],
    crosswalkConfidence: 'H',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-4-4',
    clause: 'A.4 — Resources'
  },
  'A.4.5': {
    name: 'System and Computing Resources',
    description: 'Documented compute infrastructure supporting AI systems, including capacity and security.',
    awareness: 'partial',
    awareComponents: ['agent-registry'],
    crosswalkConfidence: 'M',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-4-5',
    clause: 'A.4 — Resources'
  },
  'A.4.6': {
    name: 'Human Resources',
    description: 'AI competence requirements defined; training, hiring, and reassignment for AI roles.',
    awareness: 'gap',
    awareComponents: [],
    crosswalkConfidence: 'L',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-4-6',
    clause: 'A.4 — Resources'
  },

  // -----------------------------------------------------------------------
  // A.5 — Impact assessment (the headline AWARE gap, per ADR-055 §"Headline gap")
  // -----------------------------------------------------------------------
  'A.5.2': {
    name: 'AI-System Impact-Assessment Process',
    description: 'Documented process for assessing AI-system impact before deployment, including methodology.',
    awareness: 'gap',
    awareComponents: [],
    crosswalkConfidence: 'L',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-5-2',
    clause: 'A.5 — Impact assessment'
  },
  'A.5.3': {
    name: 'Documentation of AI-System Impact Assessments',
    description: 'Records of impact assessments retained for the lifetime of the AI system.',
    awareness: 'gap',
    awareComponents: [],
    crosswalkConfidence: 'L',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-5-3',
    clause: 'A.5 — Impact assessment'
  },
  'A.5.4': {
    name: 'Assessing AI-System Impact on Individuals or Groups of Individuals',
    description: 'Evaluation of effects on individuals and groups, including vulnerable populations.',
    awareness: 'gap',
    awareComponents: [],
    crosswalkConfidence: 'L',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-5-4',
    clause: 'A.5 — Impact assessment'
  },
  'A.5.5': {
    name: 'Assessing Societal Impacts of AI Systems',
    description: 'Broader societal-impact assessment (e.g., labour, environment, public discourse).',
    awareness: 'gap',
    awareComponents: [],
    crosswalkConfidence: 'L',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-5-5',
    clause: 'A.5 — Impact assessment'
  },

  // -----------------------------------------------------------------------
  // A.6 — AI system lifecycle (the strongest AWARE surface, per ADR-055)
  // -----------------------------------------------------------------------
  'A.6.1.2': {
    name: 'Objectives for Responsible Development of AI Systems',
    description: 'Defined objectives for responsible AI development (fairness, transparency, accountability).',
    awareness: 'partial',
    awareComponents: ['compliance-mapping'],
    crosswalkConfidence: 'M',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-6-1-2',
    clause: 'A.6 — AI system lifecycle'
  },
  'A.6.1.3': {
    name: 'Processes for Responsible AI-System Design and Development',
    description: 'Documented design and development processes aligned with responsible-AI objectives.',
    awareness: 'mapped',
    awareComponents: ['tool-access-control', 'sandbox-policies'],
    crosswalkConfidence: 'H',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-6-1-3',
    clause: 'A.6 — AI system lifecycle'
  },
  'A.6.2.2': {
    name: 'AI-System Requirements and Specification',
    description: 'Documented requirements (functional, performance, ethical, regulatory) for each AI system.',
    awareness: 'partial',
    awareComponents: ['agent-registry', 'security-heuristic'],
    crosswalkConfidence: 'M',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-6-2-2',
    clause: 'A.6 — AI system lifecycle'
  },
  'A.6.2.3': {
    name: 'Documentation of AI-System Design and Development',
    description: 'Design docs, architecture decisions, and development records retained for the lifecycle.',
    awareness: 'mapped',
    awareComponents: ['compliance-mapping'],
    crosswalkConfidence: 'H',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-6-2-3',
    clause: 'A.6 — AI system lifecycle'
  },
  'A.6.2.4': {
    name: 'AI-System Verification and Validation',
    description: 'Documented V&V procedures including accuracy, robustness, and bias testing.',
    awareness: 'mapped',
    awareComponents: ['security-heuristic', 'anomaly-detection', 'behavioral-baseline'],
    crosswalkConfidence: 'H',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-6-2-4',
    clause: 'A.6 — AI system lifecycle'
  },
  'A.6.2.5': {
    name: 'AI-System Deployment',
    description: 'Controlled deployment process including release approval, environment promotion, rollback.',
    awareness: 'partial',
    awareComponents: ['agent-registry'],
    crosswalkConfidence: 'M',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-6-2-5',
    clause: 'A.6 — AI system lifecycle'
  },
  'A.6.2.6': {
    name: 'AI-System Operation and Monitoring',
    description: 'Operational procedures and continuous monitoring during production use.',
    awareness: 'mapped',
    awareComponents: ['tool-observation-proxy', 'anomaly-detection', 'kill-switch'],
    crosswalkConfidence: 'H',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-6-2-6',
    clause: 'A.6 — AI system lifecycle'
  },
  'A.6.2.7': {
    name: 'AI-System Technical Documentation',
    description: 'Technical documentation set required for users, integrators, and auditors.',
    awareness: 'partial',
    awareComponents: ['compliance-mapping'],
    crosswalkConfidence: 'M',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-6-2-7',
    clause: 'A.6 — AI system lifecycle'
  },
  'A.6.2.8': {
    name: 'AI-System Recording of Event Logs',
    description: 'Event logs for AI-system behaviour, decisions, and operator actions (audit trail).',
    awareness: 'mapped',
    awareComponents: ['anomaly-detection', 'compliance-mapping'],
    crosswalkConfidence: 'H',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-6-2-8',
    clause: 'A.6 — AI system lifecycle'
  },

  // -----------------------------------------------------------------------
  // A.7 — Data for AI systems
  // -----------------------------------------------------------------------
  'A.7.2': {
    name: 'Data for Development and Enhancement of AI Systems',
    description: 'Defined datasets for training, testing, and ongoing enhancement, with provenance and quality gates.',
    awareness: 'partial',
    awareComponents: ['agent-registry'],
    crosswalkConfidence: 'M',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-7-2',
    clause: 'A.7 — Data for AI systems'
  },
  'A.7.3': {
    name: 'Acquisition of Data',
    description: 'Documented process for data acquisition, including licensing, consent, and source vetting.',
    awareness: 'partial',
    awareComponents: ['tool-access-control'],
    crosswalkConfidence: 'M',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-7-3',
    clause: 'A.7 — Data for AI systems'
  },
  'A.7.4': {
    name: 'Quality of Data for AI Systems',
    description: 'Data-quality criteria (accuracy, completeness, timeliness) defined and measured.',
    awareness: 'gap',
    awareComponents: ['credential-classifier'],
    crosswalkConfidence: 'L',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-7-4',
    clause: 'A.7 — Data for AI systems'
  },
  'A.7.5': {
    name: 'Data Provenance',
    description: 'Documented lineage of all data from source to current state (chain of custody).',
    awareness: 'partial',
    awareComponents: ['compliance-mapping'],
    crosswalkConfidence: 'M',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-7-5',
    clause: 'A.7 — Data for AI systems'
  },
  'A.7.6': {
    name: 'Data Preparation',
    description: 'Documented data preparation steps (cleaning, labelling, augmentation) with version control.',
    awareness: 'gap',
    awareComponents: [],
    crosswalkConfidence: 'L',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-7-6',
    clause: 'A.7 — Data for AI systems'
  },

  // -----------------------------------------------------------------------
  // A.8 — Transparency and communication
  // -----------------------------------------------------------------------
  'A.8.2': {
    name: 'System Documentation and Information for Users',
    description: 'End-user-facing documentation explaining AI-system capabilities, limits, and intended use.',
    awareness: 'partial',
    awareComponents: ['compliance-mapping'],
    crosswalkConfidence: 'M',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-8-2',
    clause: 'A.8 — Transparency and communication'
  },
  'A.8.3': {
    name: 'External Reporting',
    description: 'Public reporting on AI systems (e.g., model cards, system cards, transparency reports).',
    awareness: 'mapped',
    awareComponents: ['compliance-mapping'],
    crosswalkConfidence: 'H',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-8-3',
    clause: 'A.8 — Transparency and communication'
  },
  'A.8.4': {
    name: 'Communication of Incidents',
    description: 'Documented process for incident communication (internally, to users, to regulators).',
    awareness: 'mapped',
    awareComponents: ['kill-switch', 'anomaly-detection'],
    crosswalkConfidence: 'H',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-8-4',
    clause: 'A.8 — Transparency and communication'
  },
  'A.8.5': {
    name: 'Information for Interested Parties',
    description: 'Targeted information to affected parties (right-to-explanation, redress mechanisms).',
    awareness: 'partial',
    awareComponents: ['compliance-mapping'],
    crosswalkConfidence: 'M',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-8-5',
    clause: 'A.8 — Transparency and communication'
  },

  // -----------------------------------------------------------------------
  // A.9 — Use of AI systems
  // -----------------------------------------------------------------------
  'A.9.2': {
    name: 'Processes for Responsible Use of AI Systems',
    description: 'Documented processes for the responsible use of AI by operators and end users.',
    awareness: 'mapped',
    awareComponents: ['tool-access-control'],
    crosswalkConfidence: 'H',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-9-2',
    clause: 'A.9 — Use of AI systems'
  },
  'A.9.3': {
    name: 'Objectives for Responsible Use of AI Systems',
    description: 'Defined objectives for responsible AI use (e.g., human oversight, escalation paths).',
    awareness: 'gap',
    awareComponents: ['compliance-mapping'],
    crosswalkConfidence: 'L',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-9-3',
    clause: 'A.9 — Use of AI systems'
  },
  'A.9.4': {
    name: 'Intended use of the AI system',
    description: 'Documented intended use, including what is OUT of scope; misuse detection procedures.',
    awareness: 'mapped',
    awareComponents: ['agent-registry', 'behavioral-baseline'],
    crosswalkConfidence: 'H',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-9-4',
    clause: 'A.9 — Use of AI systems'
  },

  // -----------------------------------------------------------------------
  // A.10 — Third-party and customer
  // -----------------------------------------------------------------------
  'A.10.2': {
    name: 'Allocating Responsibilities',
    description: 'Responsibilities allocated between provider and customer for shared AI-system aspects.',
    awareness: 'partial',
    awareComponents: ['agent-registry'],
    crosswalkConfidence: 'M',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-10-2',
    clause: 'A.10 — Third-party and customer'
  },
  'A.10.3': {
    name: 'Suppliers',
    description: 'Supplier-management process for AI components, models, and services.',
    awareness: 'mapped',
    awareComponents: ['identity-provider'],
    crosswalkConfidence: 'H',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-10-3',
    clause: 'A.10 — Third-party and customer'
  },
  'A.10.4': {
    name: 'Customers',
    description: 'Customer-facing commitments, including support, incident response, and feedback channels.',
    awareness: 'partial',
    awareComponents: ['compliance-mapping'],
    crosswalkConfidence: 'M',
    ismsRef: 'https://www.isms.online/iso-42001/annex-a-controls/#a-10-4',
    clause: 'A.10 — Third-party and customer'
  }
});

/**
 * Flat list of ISO/IEC 42001:2023 Annex A control IDs in ISMS.online order
 * (preserves the upstream nav ordering; not alphabetical — operators may
 * rely on the canonical clause ordering when reading the compliance report).
 *
 * @type {string[]}
 */
const ISO_42001_CONTROL_IDS = Object.freeze(Object.keys(ISO_42001_CONTROLS));

module.exports = {
  ISO_42001_CONTROLS,
  ISO_42001_CONTROL_IDS
};
