"""
Tests for scripts/verify_chain.py — the independent stdlib-only verifier
for AWARE's decision-chain.jsonl. Five tests, each guards a distinct
contract:

    1. happy path: real fixture passes
    2. single-record tamper: hash mismatch diagnostic
    3. chain break: prevHash mismatch diagnostic
    4. genesis: first record's prevHash is the 64-zero GENESIS
    5. canonicalization fidelity: Python re-emits match JS for 5 sampled
       records (catches future drift if canonicalSerialize() changes)

The fixture is regenerated by tests/audit/fixtures/_generate_fixture.js
from AWARE's real decision-logger.js — never hand-rolled, otherwise
we'd be testing our Python against itself instead of against AWARE.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
VERIFIER = REPO_ROOT / "scripts" / "verify_chain.py"
FIXTURE = REPO_ROOT / "tests" / "audit" / "fixtures" / "aware_chain_1k.jsonl"
FIXTURE_GEN = REPO_ROOT / "tests" / "audit" / "fixtures" / "_generate_fixture.js"

# Match GENESIS_HASH in src/audit/decision-logger.js:25
GENESIS = "0" * 64


def _run_verifier(*args, env=None):
    """Run verify_chain.py with the given args; return (returncode, stdout, stderr)."""
    proc = subprocess.run(
        [sys.executable, str(VERIFIER), *args],
        capture_output=True,
        text=True,
        env=env,
        timeout=60,
    )
    return proc.returncode, proc.stdout, proc.stderr


# ---------------------------------------------------------------------------
# Test 1: happy path — the canonical 1k fixture verifies cleanly.
# ---------------------------------------------------------------------------

def test_happy_path_real_fixture_passes():
    assert FIXTURE.exists(), (
        f"Fixture missing at {FIXTURE}. Re-run: node {FIXTURE_GEN} 1000 {FIXTURE}"
    )
    rc, out, err = _run_verifier(str(FIXTURE))
    assert rc == 0, f"verifier exited {rc}; stderr={err!r}"
    assert "PASS verified 1000 records" in out, f"unexpected stdout: {out!r}"


# ---------------------------------------------------------------------------
# Test 2: single-record tamper — flip one byte in record #500's hash,
# expect a hash-mismatch diagnostic with the line number.
# ---------------------------------------------------------------------------

def test_single_record_tamper_detected(tmp_path):
    shutil.copy(FIXTURE, tmp_path / "tampered.jsonl")
    tampered = tmp_path / "tampered.jsonl"
    lines = tampered.read_text(encoding="utf-8").splitlines()
    # Flip the first hex char of record #500's hash field.
    target_idx = 499  # 0-based
    record = json.loads(lines[target_idx])
    original_hash = record["hash"]
    record["hash"] = ("f" if original_hash[0] != "f" else "0") + original_hash[1:]
    lines[target_idx] = json.dumps(record, separators=(",", ":"))
    tampered.write_text("\n".join(lines) + "\n", encoding="utf-8")

    rc, out, err = _run_verifier(str(tampered))
    assert rc == 1, f"expected exit 1 on tamper, got {rc}"
    assert f"line {target_idx + 1}" in err, f"missing line number in: {err!r}"
    assert "hash mismatch" in err, f"missing 'hash mismatch' in: {err!r}"


# ---------------------------------------------------------------------------
# Test 3: chain break — delete record #500, expect prevHash mismatch.
# ---------------------------------------------------------------------------

def test_chain_break_detected(tmp_path):
    shutil.copy(FIXTURE, tmp_path / "broken.jsonl")
    broken = tmp_path / "broken.jsonl"
    lines = broken.read_text(encoding="utf-8").splitlines()
    del lines[499]  # remove record #500
    broken.write_text("\n".join(lines) + "\n", encoding="utf-8")

    rc, out, err = _run_verifier(str(broken))
    assert rc == 1, f"expected exit 1 on chain break, got {rc}"
    assert "line 500" in err, f"expected line 500, got: {err!r}"
    assert "chain break" in err, f"missing 'chain break' in: {err!r}"


# ---------------------------------------------------------------------------
# Test 4: genesis — first record's prevHash is exactly GENESIS.
# ---------------------------------------------------------------------------

def test_first_record_uses_genesis_prevhash():
    with FIXTURE.open(encoding="utf-8") as f:
        first = json.loads(next(f))
    assert first["prevHash"] == GENESIS, (
        f"first record prevHash should be GENESIS (64 zeros); got {first['prevHash']!r}"
    )
    assert first["parentDecisionId"] is None, (
        f"first record parentDecisionId should be null; got {first['parentDecisionId']!r}"
    )


# ---------------------------------------------------------------------------
# Test 5: canonicalization fidelity — re-implement the JS canonical form
# for 5 sampled records and assert Python's recompute_hash matches.
#
# This is the test that would catch a future change to
# canonicalSerialize() in decision-logger.js:71-93 — if the JS side
# ever drops the explicit fieldOrder, or starts recursively sorting
# nested keys, or changes separators, the hash will not match the
# Python side and this test will fail.
# ---------------------------------------------------------------------------

# These top-level fields MUST appear in the canonical serialization
# (per canonicalSerialize's fieldOrder in decision-logger.js:73-83),
# sorted alphabetically. The verifier's encode() must sort them in this
# exact order.
EXPECTED_TOP_ORDER = [
    "action", "actor", "context", "decisionId",
    "outcome", "parentDecisionId", "prevHash", "timestamp",
]


def _canonical_for_test(record):
    """Re-implementation of the canonical-form contract used for fidelity check.

    We don't call verify_chain.canonical_payload() here on purpose: this
    test validates that an independent re-implementation of the same
    rules produces the same hash. The two implementations have to agree
    bit-for-bit; if either drifts, this test fails.
    """
    sans = {k: v for k, v in record.items() if k != "hash"}
    # Sort only at the top level; preserve nested insertion order
    # (matching JS JSON.stringify behavior).
    ordered = {k: sans[k] for k in EXPECTED_TOP_ORDER if k in sans}
    return json.dumps(ordered, separators=(",", ":"), sort_keys=False)


def test_canonicalization_fidelity_against_js():
    """5 sampled records: independent Python canonical-form agrees with AWARE's hash."""
    sample_indices = [0, 250, 500, 750, 999]
    with FIXTURE.open(encoding="utf-8") as f:
        lines = f.readlines()
    for idx in sample_indices:
        record = json.loads(lines[idx])
        canon = _canonical_for_test(record)
        expected = hashlib.sha256(
            (canon + record["prevHash"]).encode("utf-8")
        ).hexdigest()
        assert expected == record["hash"], (
            f"canonical mismatch at line {idx + 1}: "
            f"expected {expected}, got {record['hash']}; canonical={canon!r}"
        )