"""
AWARE × Vaara integration test — shadow-mode audit backend.

Spec: t_13d38c3a (parent: t_0eab8376). The adapter is `VaaraAuditBackend`
in `src/coordinator/adapters/vaara.js` — a thin HTTP client against the
Vaara HTTP API (`vaara serve`) that implements the same surface as
`src/audit/decision-logger.js` so the gateway can swap backends via
`AWARE_AUDIT_BACKEND=vaara` (default `file`).

The adapter exposes a tiny CLI for testability: feed NDJSON decisions
on stdin, get NDJSON `decision-chain.jsonl` lines on stdout. That
keeps the test runner (pytest) decoupled from the Node source tree.

Design corrections vs. the original card body (see kanban comment 1203
on t_13d38c3a): integration is via Vaara's HTTP API
(POST /v1/audit/events → AuditEventResponse), not by spawning
`vaara-mcp-proxy --shadow` and parsing NDJSON envelopes from stdout.
`--shadow` semantics map to "record every call, never block, fall open
on verification failure with a WARN log."

Fixture: `tests/audit/fixtures/vaara_v130.jsonl` — 50 deterministic
mock Vaara AuditEventResponse objects with a valid hash chain
(record_hash[N].attestationDigest == record_hash[N-1]). Generated by
`tests/audit/regenerate_fixture.py`.

Run:
    pytest tests/audit/test_vaara_integration.py -v
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import socket
import subprocess
import tempfile
import threading
import time
from contextlib import contextmanager
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
ADAPTER_PATH = REPO_ROOT / "src" / "coordinator" / "adapters" / "vaara.js"
FIXTURE_PATH = (
    REPO_ROOT / "tests" / "audit" / "fixtures" / "vaara_v130.jsonl"
)
DECISION_LOGGER_PATH = REPO_ROOT / "src" / "audit" / "decision-logger.js"
CLI_TIMEOUT_SECONDS = 30


# ---------------------------------------------------------------------------
# Mock Vaara HTTP server (no upstream dependency)
# ---------------------------------------------------------------------------


# Module-level mock state, set per-test by MockVaara.start(). Reading
# from the class attr triggers a metaclass conflict in some pyright
# versions; a module attr avoids the whole class-body namespace dance.
_CURRENT_MOCK: "MockVaara | None" = None


class MockVaaraHandler(BaseHTTPRequestHandler):
    """In-memory Vaara HTTP API.

    Implements three endpoints enough for the adapter to function:
      POST /v1/audit/events   → appendAuditEvent
      GET  /v1/audit/verify   → verifyAuditChain
      GET  /v1/health         → serverInfo/health probe

    `state['chain']` is the canonical receipt chain: list of dicts,
    each with `record_id`, `record_hash`, `previous_hash`, `timestamp`.
    `state['fail_next_verify']` toggles a deliberate verify failure
    so we can exercise the falls-open path.
    """

    def log_message(self, format, *args):  # silence stderr noise
        return

    def _mock(self) -> "MockVaara":
        assert _CURRENT_MOCK is not None, "MockVaara.start() not called"
        return _CURRENT_MOCK

    def _json(self, status, body):
        payload = json.dumps(body).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def do_POST(self):
        length = int(self.headers.get("Content-Length", "0"))
        body = json.loads(self.rfile.read(length) or "{}")
        if self.path.endswith("/audit/events"):
            return self._handle_append(body)
        self._json(404, {"error": "not_found"})

    def do_GET(self):
        if self.path.endswith("/audit/verify"):
            return self._handle_verify()
        if self.path.endswith("/health"):
            return self._json(200, {"status": "ok"})
        self._json(404, {"error": "not_found"})

    def _handle_append(self, body):
        chain = self._mock().state["chain"]
        prev_hash = chain[-1]["record_hash"] if chain else (
            "0" * 64
        )
        # Canonical preimage: SHA-256 of JSON-canonical body + prev_hash.
        # Matches the @vaara/client surface (record_hash is server-side).
        canonical = json.dumps(body, sort_keys=True, separators=(",", ":"))
        digest = hashlib.sha256(
            (canonical + prev_hash).encode("utf-8")
        ).hexdigest()
        record = {
            "record_id": f"rec_{len(chain) + 1:04d}",
            "record_hash": digest,
            "previous_hash": prev_hash,
            "timestamp": time.strftime(
                "%Y-%m-%dT%H:%M:%S.000Z", time.gmtime()
            ),
            "payload": body,
        }
        chain.append(record)
        self._json(201, {
            "record_id": record["record_id"],
            "record_hash": record["record_hash"],
            "previous_hash": record["previous_hash"],
            "timestamp": record["timestamp"],
        })

    def _handle_verify(self):
        mock = self._mock()
        if mock.state.get("fail_next_verify"):
            # Deliberate break: claim chain is valid but flip one hash.
            return self._json(200, {
                "valid": False,
                "events_checked": len(mock.state["chain"]),
                "first_break": {
                    "event_id": "rec_0001",
                    "chain_position": 0,
                    "expected_previous_hash": "f" * 64,
                    "actual_previous_hash": mock.state["chain"][0][
                        "previous_hash"
                    ] if mock.state["chain"] else "0" * 64,
                },
            })
        return self._json(200, {
            "valid": True,
            "events_checked": len(mock.state["chain"]),
        })


class MockVaara:
    """Wraps MockVaaraHandler + spins a real HTTPServer on a free port."""

    def __init__(self):
        self.state = {"chain": [], "fail_next_verify": False}
        self._server = None
        self._thread = None
        self.port = None

    def start(self):
        global _CURRENT_MOCK
        _CURRENT_MOCK = self
        self._server = HTTPServer(("127.0.0.1", 0), MockVaaraHandler)
        self.port = self._server.server_address[1]
        self._thread = threading.Thread(
            target=self._server.serve_forever, daemon=True
        )
        self._thread.start()

    def stop(self):
        global _CURRENT_MOCK
        if self._server is not None:
            self._server.shutdown()
            self._server.server_close()
            self._server = None
        if _CURRENT_MOCK is self:
            _CURRENT_MOCK = None


@contextmanager
def mock_vaara():
    server = MockVaara()
    server.start()
    try:
        yield server
    finally:
        server.stop()


# ---------------------------------------------------------------------------
# CLI invocation helper
# ---------------------------------------------------------------------------


def _free_port() -> int:
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _run_cli(
    env_overrides: dict,
    decisions_ndjson: str,
    workdir: Path,
) -> subprocess.CompletedProcess:
    """Spawn the adapter as a subprocess and feed decisions on stdin."""
    env = os.environ.copy()
    env.update(env_overrides)
    # Sanity: adapter file must exist
    assert ADAPTER_PATH.exists(), f"missing adapter: {ADAPTER_PATH}"
    proc = subprocess.run(
        ["node", str(ADAPTER_PATH), "run"],
        input=decisions_ndjson,
        capture_output=True,
        text=True,
        env=env,
        cwd=workdir,
        timeout=CLI_TIMEOUT_SECONDS,
    )
    return proc


def _make_decisions(n: int) -> str:
    """Generate N synthetic decisions in NDJSON."""
    out = []
    for i in range(n):
        out.append(json.dumps({
            "decisionId": f"dec_{i:04d}",
            "parentDecisionId": f"dec_{i - 1:04d}" if i > 0 else None,
            "timestamp": "2026-07-15T10:00:00.000Z",
            "actor": {"agentId": "agent-007", "trustScore": 0.9},
            "action": {"type": "tool_call", "target": f"mcp://tool/{i}"},
            "context": {},
            "outcome": {"success": True, "latencyMs": 12, "errorMessage": None},
        }))
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def tmp_aware(tmp_path):
    """Isolated AWARE workspace: copy the audit module + adapter so the
    CLI can find them without polluting the source tree."""
    audit_dst = tmp_path / "src" / "audit"
    adapters_dst = tmp_path / "src" / "coordinator" / "adapters"
    audit_dst.mkdir(parents=True)
    adapters_dst.mkdir(parents=True)
    shutil.copy2(DECISION_LOGGER_PATH, audit_dst / "decision-logger.js")
    shutil.copy2(ADAPTER_PATH, adapters_dst / "vaara.js")
    audit_dir = tmp_path / "data" / "audit"
    audit_dir.mkdir(parents=True)
    return tmp_path


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


def test_adapter_file_exists_and_is_under_200_loc():
    """AC: adapter file exists, ≤200 LOC, no new runtime deps."""
    assert ADAPTER_PATH.exists(), f"missing adapter at {ADAPTER_PATH}"
    loc = sum(1 for line in ADAPTER_PATH.read_text().splitlines()
              if line.strip() and not line.strip().startswith("//"))
    assert loc <= 200, f"adapter is {loc} non-comment LOC; must be ≤200"


def test_no_new_runtime_deps():
    """AC: no new runtime deps. We assert no `require(...)` outside the
    Node built-in surface and no new entry in package.json."""
    pkg = json.loads((REPO_ROOT / "package.json").read_text())
    deps = pkg.get("dependencies", {})
    # No new entries added by this card. `@vaara/client` would be the
    # candidate; assert it's absent.
    assert "@vaara/client" not in deps, (
        "card mandates no new runtime deps; @vaara/client must NOT be added"
    )
    # And the adapter source must only require built-ins.
    src = ADAPTER_PATH.read_text()
    for needle in ("require(", "from \""):
        if needle in src:
            # Pull out require paths.
            import re
            for match in re.findall(r"require\\(['\"]([^'\"]+)['\"]\\)", src):
                # Built-ins: node:* and bare names like `fs`, `crypto`,
                # `http`, `url`, `path`. Relative paths start with `.`.
                assert match.startswith(".") or match.startswith(
                    "node:"
                ) or match in {
                    "fs", "crypto", "http", "https", "url", "path",
                    "stream", "child_process", "os", "util", "events",
                }, f"non-builtin require: {match}"


def test_hash_chain_continuity_n50_round_trips(tmp_aware):
    """AC: hash-chain continuity across N=50 tool-call round trips
    against a recorded fixture of real vaara.receipt/v1 envelopes."""
    with mock_vaara() as server:
        decisions = _make_decisions(50)
        result = _run_cli(
            env_overrides={
                "AWARE_AUDIT_BACKEND": "vaara",
                "VAARA_BASE_URL": f"http://127.0.0.1:{server.port}",
                "VAARA_SHADOW": "1",
                "AUDIT_DIR": str(tmp_aware / "data" / "audit"),
                "VAARA_VERIFY_MODE": "per-record",  # verify each round trip
            },
            decisions_ndjson=decisions,
            workdir=tmp_aware,
        )
    assert result.returncode == 0, (
        f"adapter CLI exited {result.returncode}; "
        f"stderr={result.stderr!r}"
    )

    chain_file = tmp_aware / "data" / "audit" / "decision-chain.jsonl"
    assert chain_file.exists(), "decision-chain.jsonl not written"
    lines = [
        json.loads(line)
        for line in chain_file.read_text().splitlines()
        if line.strip()
    ]
    assert len(lines) == 50, f"expected 50 entries, got {len(lines)}"

    # Chain continuity on the AWARE side (decision-logger prevHash linkage).
    for i, rec in enumerate(lines):
        expected_prev = (
            "0" * 64 if i == 0 else lines[i - 1]["hash"]
        )
        assert rec["prevHash"] == expected_prev, (
            f"record {i} prevHash broken: "
            f"expected {expected_prev}, got {rec['prevHash']}"
        )

    # Every entry must have verified=true (mock server reported valid).
    for rec in lines:
        assert rec.get("verified") is True, (
            f"record {rec['decisionId']} verified={rec.get('verified')!r}; "
            f"expected True (mock server reports valid)"
        )

    # The mock server's receipt chain must also be continuous — every
    # receipt's record_hash is the SHA-256 of canonical(body + prev_hash),
    # so we recompute and check.
    server_chain = server.state["chain"]
    assert len(server_chain) == 50
    for i, rec in enumerate(server_chain):
        if i == 0:
            assert rec["previous_hash"] == "0" * 64
        else:
            assert rec["previous_hash"] == server_chain[i - 1]["record_hash"], (
                f"server-side chain broken at record {i}"
            )


def test_verification_failure_falls_open_with_warn(tmp_aware):
    """AC: when verification fails, decision-chain.jsonl still gets the
    entry but with verified=false and a structured warning log; tool
    call is not blocked."""
    with mock_vaara() as server:
        server.state["fail_next_verify"] = True
        decisions = _make_decisions(3)
        result = _run_cli(
            env_overrides={
                "AWARE_AUDIT_BACKEND": "vaara",
                "VAARA_BASE_URL": f"http://127.0.0.1:{server.port}",
                "VAARA_SHADOW": "1",
                "AUDIT_DIR": str(tmp_aware / "data" / "audit"),
                "VAARA_VERIFY_MODE": "per-record",
            },
            decisions_ndjson=decisions,
            workdir=tmp_aware,
        )
    # Tool call is NOT blocked — the adapter still exits 0.
    assert result.returncode == 0, (
        f"adapter blocked the call when it should fall open; "
        f"stderr={result.stderr!r}"
    )
    chain_file = tmp_aware / "data" / "audit" / "decision-chain.jsonl"
    lines = [
        json.loads(line)
        for line in chain_file.read_text().splitlines()
        if line.strip()
    ]
    assert len(lines) == 3, "all 3 decisions still recorded"
    for rec in lines:
        assert rec.get("verified") is False, (
            f"record {rec['decisionId']} should have verified=false on "
            f"verification failure"
        )
    # Structured WARN logged to stderr.
    assert "[vaara-audit]" in result.stderr and "WARN" in result.stderr, (
        f"expected structured WARN in stderr; got: {result.stderr!r}"
    )


def test_file_backend_regression_guard(tmp_aware):
    """AC: AWARE_AUDIT_BACKEND=file still works byte-identical to before.

    Drives the same 5 decisions through the file backend and verifies
    the output matches what `decision-logger.js` writes standalone (no
    adapter involvement). Proves the adapter is purely additive."""
    decisions = _make_decisions(5)

    # Run 1: via adapter, file backend selected. Adapter must NOT
    # touch the chain — it should pass-through to decision-logger.
    result = _run_cli(
        env_overrides={
            "AWARE_AUDIT_BACKEND": "file",
            "AUDIT_DIR": str(tmp_aware / "data" / "audit"),
        },
        decisions_ndjson=decisions,
        workdir=tmp_aware,
    )
    assert result.returncode == 0, result.stderr
    via_adapter = (
        tmp_aware / "data" / "audit" / "decision-chain.jsonl"
    ).read_text()

    # Run 2: standalone decision-logger (no adapter in the loop).
    audit_dir2 = tmp_aware / "data2" / "audit"
    audit_dir2.mkdir(parents=True)
    standalone = subprocess.run(
        [
            "node",
            "-e",
            f"""
            const dl = require('./src/audit/decision-logger.js');
            const fs = require('fs');
            const lines = fs.readFileSync(0, 'utf8').split('\\n').filter(Boolean);
            (async () => {{
              for (const line of lines) {{
                await dl.logDecision(JSON.parse(line));
              }}
            }})();
            """,
        ],
        input=decisions,
        capture_output=True,
        text=True,
        env={
            **os.environ,
            "AUDIT_DIR": str(audit_dir2),
        },
        cwd=tmp_aware,
        timeout=CLI_TIMEOUT_SECONDS,
    )
    assert standalone.returncode == 0, standalone.stderr
    via_standalone = (audit_dir2 / "decision-chain.jsonl").read_text()

    # Both should produce the same line count and the same `hash` /
    # `prevHash` structure. Timestamps can differ (sub-second), so we
    # compare line-by-line on the hash chain only.
    adapter_lines = [
        json.loads(l) for l in via_adapter.splitlines() if l.strip()
    ]
    standalone_lines = [
        json.loads(l) for l in via_standalone.splitlines() if l.strip()
    ]
    assert len(adapter_lines) == len(standalone_lines) == 5
    for a, s in zip(adapter_lines, standalone_lines):
        # Same fields, same order — verified by sorting and comparing
        sorted_a = json.dumps(a, sort_keys=True)
        sorted_s = json.dumps(s, sort_keys=True)
        assert sorted_a == sorted_s, (
            f"regression: file-backend output drifted via adapter\n"
            f"  adapter:    {sorted_a}\n"
            f"  standalone: {sorted_s}"
        )


def test_fixture_is_reproducible_and_canonical():
    """The committed fixture (vaara_v130.jsonl) must be deterministic
    and regenerable by regenerate_fixture.py."""
    if not FIXTURE_PATH.exists():
        pytest.skip("fixture not present yet — regenerate_fixture.py ships it")
    lines = [
        json.loads(l) for l in FIXTURE_PATH.read_text().splitlines()
        if l.strip()
    ]
    # Fixture must have exactly 50 records per the AC.
    assert len(lines) == 50, (
        f"fixture has {len(lines)} records; spec is 50 round trips"
    )
    # Chain must be internally consistent.
    for i, rec in enumerate(lines):
        if i == 0:
            assert rec["previous_hash"] == "0" * 64
        else:
            assert rec["previous_hash"] == lines[i - 1]["record_hash"]